image:
  repository: ghcr.io/ms-boom/contraction-example-1
  tag: 8d5bcebf538b4c9b015677b2e0d42ca31387db57
ingress:
  enabled: true
postgres:
  enabled: true
replicaCount: 1
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  port: 8080
