image:
  repository: ghcr.io/ms-boom/contraction-example-1
  tag: 9cb44b4485d366525f905fb5f00f365ab16f4270
ingress:
  enabled: true
replicaCount: 1
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  port: 8080
