image:
  repository: ghcr.io/ms-boom/contraction-example-1
  tag: 7934ea80599971bdd61c36050ba00e12de090206
ingress:
  enabled: true
replicaCount: 1
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  port: 8080
