image:
  repository: ghcr.io/ms-boom/contraction-example-1
  tag: 14390802bd3242da98ec0729c4433593f1d80372
ingress:
  enabled: true
replicaCount: 1
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  port: 8080
